# A configuration for Metrician that control features of our
# automated metric reporting

---

# "request_timing" settings control the Rack timing middleware's features
:request_timing:
  # allow insertion of Rack middleware for request timing
  :enabled: true

  # collect basic request timing for every request
  :request:
    :enabled: true

  # report 5xx codes as errors
  :error:
    :enabled: true

  # report time between requests in a server process as idle time
  :idle:
    :enabled: false

  # report the payload size of requests
  :response_size:
    :enabled: false

  # report the amount of time spent on middleware per request
  :middleware:
    :enabled: false

  # report the amount of time a request spent queued at the web layer
  # before hitting Rack
  :queue_time:
    :enabled: false

  # report the controller, action, and verb for every request
  :route_tracking:
    :enabled: false


# "database" settings control ActiveRecord metric reporting features
:database:
  # allow insertion of ActiveRecord adapter
  :enabled: true

  # collect basic query tracking for every query
  :query:
    :enabled: true

  # collect generic sql query information (select, update, insert, etc.)
  :sql:
    :enabled: false

  # collect query information for specific tables and ActiveRecord
  # based queries (find, update, destroy)
  :active_record:
    :enabled: false


# "external_service" settings control reporting metrics when Net::HTTP
# is used to make requests
:external_service:
  # insert Net::HTTP monkey patch to record metrics
  :enabled: true

  # collect basic external request timing information
  :request:
    :enabled: true


# "queue" settings control reporting metrics when ruby job systems
# work through their job queues
:queue:

  # insert job system middleware and monkey patches when presence detected
  :enabled: true

  # record the basic timing of every job
  :process:
    :enabled: true

  # record when an error occurs in the a job
  :error:
    :enabled: true

  # record metrics for each kind of job that is worked from the queue
  :job_specific:
    :enabled: false

# "cache" settings control timing of commands to services often used as
# application caches like memcached and redis
:cache:

  # insert cache system tracking and monkey patching
  :enabled: true

  # record the basic timing of every command
  :command:
    :enabled: true

  # record the timing of each command as its own metric
  :command_specific:
    :enabled: false


# "exception" settings control reporting when exceptions are caught
# by an exception tracker in your application
:exception:

  # insert exception tracking instrumenation and monkey patching
  :enabled: false

  # report when an exception is raised and caught by an exception tracker
  :raise:
    :enabled: true

  # report a metric per exception type raised
  :exception_specific:
    :enabled: false
